export const FILTER_OPTIONS = [
  { id: 'all', label: 'All' },
  { id: 'turmeric', label: 'Turmeric' },
  { id: 'ginger', label: 'Ginger' },
  { id: 'ashwagandha', label: 'Ashwagandha' },
  { id: 'approved', label: 'Approved' },
];

export const BATCH_DATA = [
  {
    id: 'TUR2024001',
    name: 'Organic Turmeric',
    farmer: 'Kerala Farms, Kochi',
    weight: '250kg',
    status: 'Approved',
    statusColor: 'green',
    received: '2 days ago',
    certifications: ['Organic Certified', 'FSSAI Approved', 'ISO 22000'],
    temperature: '18°C',
    humidity: '45%',
    origin: 'Kerala, India',
    harvestDate: '2024-01-15',
  },
  {
    id: 'GIN2024002',
    name: 'Fresh Ginger',
    farmer: 'Himalayan Herbs, Shimla',
    weight: '180kg',
    status: 'Pending',
    statusColor: 'yellow',
    received: '1 day ago',
    certifications: ['Organic Certified'],
    temperature: '16°C',
    humidity: '50%',
    origin: 'Himachal Pradesh, India',
    harvestDate: '2024-01-20',
  },
  {
    id: 'ASH2024003',
    name: 'Ashwagandha Root',
    farmer: 'Rajasthan Organics, Jaipur',
    weight: '320kg',
    status: 'Approved',
    statusColor: 'green',
    received: '3 hours ago',
    certifications: ['Organic Certified', 'GAP Certified'],
    temperature: '20°C',
    humidity: '40%',
    origin: 'Rajasthan, India',
    harvestDate: '2024-01-22',
  },
  {
    id: 'TUL2024004',
    name: 'Holy Basil (Tulsi)',
    farmer: 'Gujarat Herbs, Ahmedabad',
    weight: '95kg',
    status: 'Pending',
    statusColor: 'yellow',
    received: '5 hours ago',
    certifications: [],
    temperature: '19°C',
    humidity: '48%',
    origin: 'Gujarat, India',
    harvestDate: '2024-01-25',
  },
];