"""initial schema

Revision ID: 41fd146e4a7e
Revises: 
Create Date: 2026-05-13 20:11:29.770311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fd146e4a7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'transporter', 'lab', 'manufacturer', 'consumer', 'admin', name='user_role'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('language_pref', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('herbs',
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('farmer_id', sa.String(length=50), nullable=False),
    sa.Column('species_name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_herbs_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('qr_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_manufacturer_id'), ['manufacturer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)

    op.create_table('batch_events',
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'TRANSFER', 'LAB_REPORT', 'PRODUCT_LINK', 'INTENT_LAB_REQUEST', 'INTENT_MANUFACTURER_ORDER', name='batch_event_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('from_party_id', sa.String(length=50), nullable=True),
    sa.Column('to_party_id', sa.String(length=50), nullable=True),
    sa.Column('phase_before', sa.String(length=50), nullable=True),
    sa.Column('phase_after', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('qr_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['herbs.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_party_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['to_party_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('batch_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_events_event_type'), ['event_type'], unique=False)

    op.create_table('batch_states',
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('current_holder_id', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.Enum('with_farmer', 'in_transit_to_lab', 'at_lab', 'with_farmer_after_lab', 'in_transit_to_manufacturer', 'with_manufacturer', 'consumed', name='batch_phase'), nullable=False),
    sa.Column('test_result', sa.Enum('pending', 'approved', 'rejected', name='batch_test_result'), nullable=False),
    sa.Column('current_qr_token', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['herbs.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_holder_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    with op.batch_alter_table('batch_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_states_current_holder_id'), ['current_holder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_states_phase'), ['phase'], unique=False)

    op.create_table('lab_reports',
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('lab_id', sa.String(length=50), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('results_summary', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Enum('approved', 'rejected', name='lab_outcome'), nullable=False),
    sa.Column('certification_level', sa.String(length=50), nullable=True),
    sa.Column('purity_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('moisture_content', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ash_content', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heavy_metals_present', sa.Boolean(), nullable=True),
    sa.Column('pesticides_detected', sa.Boolean(), nullable=True),
    sa.Column('active_compounds', sa.Text(), nullable=True),
    sa.Column('potency_rating', sa.String(length=20), nullable=True),
    sa.Column('report_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['herbs.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_reports_batch_id'), ['batch_id'], unique=False)

    op.create_table('product_batch_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['herbs.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_batch_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_batch_links_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_batch_links_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_batch_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_batch_links_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_batch_links_batch_id'))

    op.drop_table('product_batch_links')
    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_reports_batch_id'))

    op.drop_table('lab_reports')
    with op.batch_alter_table('batch_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_states_phase'))
        batch_op.drop_index(batch_op.f('ix_batch_states_current_holder_id'))

    op.drop_table('batch_states')
    with op.batch_alter_table('batch_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_batch_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_batch_events_batch_id'))

    op.drop_table('batch_events')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_manufacturer_id'))

    op.drop_table('products')
    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_herbs_farmer_id'))

    op.drop_table('herbs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
