"""Add farmer features: catalogue, farm_profile, crop_plans, price_quotes, weather, batch split

Revision ID: 437a32cecbe4
Revises: 41fd146e4a7e
Create Date: 2026-05-14 14:30:15.375749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437a32cecbe4'
down_revision = '41fd146e4a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herb_catalogue',
    sa.Column('species_id', sa.String(length=50), nullable=False),
    sa.Column('common_name', sa.String(length=120), nullable=False),
    sa.Column('scientific_name', sa.String(length=160), nullable=False),
    sa.Column('ayush_category', sa.Enum('ayurveda', 'unani', 'siddha', 'homeopathy', 'general', name='ayush_category'), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('medicinal_uses', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('season_planting', sa.String(length=80), nullable=True),
    sa.Column('season_harvest', sa.String(length=80), nullable=True),
    sa.Column('default_unit_price_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('species_id')
    )
    with op.batch_alter_table('herb_catalogue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_herb_catalogue_common_name'), ['common_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_herb_catalogue_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_herb_catalogue_scientific_name'), ['scientific_name'], unique=False)

    op.create_table('weather_snapshots',
    sa.Column('snapshot_id', sa.String(length=50), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=False),
    sa.Column('gps_lng', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_snapshots_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_snapshots_gps_lat'), ['gps_lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_snapshots_gps_lng'), ['gps_lng'], unique=False)

    op.create_table('crop_plans',
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('farmer_id', sa.String(length=50), nullable=False),
    sa.Column('species_id', sa.String(length=50), nullable=False),
    sa.Column('area_acres', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=False),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'sown', 'growing', 'harvested', 'cancelled', name='crop_plan_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['herb_catalogue.species_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    with op.batch_alter_table('crop_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_plans_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_plans_species_id'), ['species_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_plans_status'), ['status'], unique=False)

    op.create_table('farm_profiles',
    sa.Column('farm_id', sa.String(length=50), nullable=False),
    sa.Column('farmer_id', sa.String(length=50), nullable=False),
    sa.Column('farm_name', sa.String(length=120), nullable=True),
    sa.Column('land_size_acres', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('soil_type', sa.Enum('alluvial', 'black', 'red', 'laterite', 'sandy', 'loamy', 'clay', 'saline', 'other', name='farm_soil_type'), nullable=True),
    sa.Column('irrigation_type', sa.Enum('rainfed', 'drip', 'sprinkler', 'flood', 'borewell', 'canal', 'mixed', 'other', name='farm_irrigation_type'), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('farm_id')
    )
    with op.batch_alter_table('farm_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_profiles_farmer_id'), ['farmer_id'], unique=True)

    op.create_table('price_quotes',
    sa.Column('quote_id', sa.String(length=50), nullable=False),
    sa.Column('species_id', sa.String(length=50), nullable=False),
    sa.Column('price_per_kg_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['herb_catalogue.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_quotes_effective_at'), ['effective_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_quotes_species_id'), ['species_id'], unique=False)

    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_batch_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_herbs_parent_batch_id'), ['parent_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_herbs_species_id'), ['species_id'], unique=False)
        batch_op.create_foreign_key('fk_herbs_species_catalogue', 'herb_catalogue', ['species_id'], ['species_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_herbs_parent_batch', 'herbs', ['parent_batch_id'], ['batch_id'], ondelete='SET NULL')

    # Extend batch_events.event_type CHECK constraint to allow BATCH_SPLIT.
    # SQLite stores the Enum as a CHECK; recreate the column with the new set.
    new_event_type = sa.Enum(
        'CREATED',
        'TRANSFER',
        'LAB_REPORT',
        'PRODUCT_LINK',
        'INTENT_LAB_REQUEST',
        'INTENT_MANUFACTURER_ORDER',
        'BATCH_SPLIT',
        name='batch_event_type',
    )
    with op.batch_alter_table('batch_events', schema=None) as batch_op:
        batch_op.alter_column(
            'event_type',
            existing_type=sa.String(length=50),
            type_=new_event_type,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    old_event_type = sa.Enum(
        'CREATED',
        'TRANSFER',
        'LAB_REPORT',
        'PRODUCT_LINK',
        'INTENT_LAB_REQUEST',
        'INTENT_MANUFACTURER_ORDER',
        name='batch_event_type',
    )
    with op.batch_alter_table('batch_events', schema=None) as batch_op:
        batch_op.alter_column(
            'event_type',
            existing_type=sa.String(length=50),
            type_=old_event_type,
            existing_nullable=False,
        )

    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_herbs_parent_batch', type_='foreignkey')
        batch_op.drop_constraint('fk_herbs_species_catalogue', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_herbs_species_id'))
        batch_op.drop_index(batch_op.f('ix_herbs_parent_batch_id'))
        batch_op.drop_column('parent_batch_id')
        batch_op.drop_column('species_id')

    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_quotes_species_id'))
        batch_op.drop_index(batch_op.f('ix_price_quotes_effective_at'))

    op.drop_table('price_quotes')
    with op.batch_alter_table('farm_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_profiles_farmer_id'))

    op.drop_table('farm_profiles')
    with op.batch_alter_table('crop_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_plans_status'))
        batch_op.drop_index(batch_op.f('ix_crop_plans_species_id'))
        batch_op.drop_index(batch_op.f('ix_crop_plans_farmer_id'))

    op.drop_table('crop_plans')
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_gps_lng'))
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_gps_lat'))
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_fetched_at'))

    op.drop_table('weather_snapshots')
    with op.batch_alter_table('herb_catalogue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_herb_catalogue_scientific_name'))
        batch_op.drop_index(batch_op.f('ix_herb_catalogue_is_active'))
        batch_op.drop_index(batch_op.f('ix_herb_catalogue_common_name'))

    op.drop_table('herb_catalogue')
    # ### end Alembic commands ###
