"""
Curated AYUSH herb catalogue — 25 species seeded into `herb_catalogue`.

Each entry:
    species_id      stable slug, used as PK and in FKs
    common_name     friendly name shown in the app
    scientific_name binomial, used by recognition for re-rank
    synonyms        regional names + variant spellings (lookup keys for AI rerank)
    season_*        rough planting / harvest windows for India
    default_unit_price_inr   indicative price per kg (seed also drops a fresher PriceQuote)
"""
from __future__ import annotations


AYUSH_SPECIES: list[dict] = [
    {
        "species_id": "ashwagandha",
        "common_name": "Ashwagandha",
        "scientific_name": "Withania somnifera",
        "synonyms": ["Indian Ginseng", "Asgandh", "Winter Cherry"],
        "description": "A small evergreen shrub with orange-red berries, prized in Ayurveda as a Rasayana (rejuvenator).",
        "medicinal_uses": "Adaptogen for stress and fatigue; supports immunity; traditionally used for vigour and sleep.",
        "image_url": "https://images.unsplash.com/photo-1581344947731-30e08e7f8b71?w=600",
        "season_planting": "Jun-Aug",
        "season_harvest": "Jan-Mar",
        "default_unit_price_inr": 320.0,
    },
    {
        "species_id": "tulsi",
        "common_name": "Tulsi",
        "scientific_name": "Ocimum sanctum",
        "synonyms": ["Holy Basil", "Tulasi", "Sacred Basil", "Ocimum tenuiflorum"],
        "description": "Sacred plant in Indian tradition, with strongly aromatic leaves.",
        "medicinal_uses": "Respiratory health; cough and cold relief; stress relief; antioxidant.",
        "image_url": "https://images.unsplash.com/photo-1597174928038-2c46c11fe9a8?w=600",
        "season_planting": "Mar-May",
        "season_harvest": "Aug-Oct",
        "default_unit_price_inr": 180.0,
    },
    {
        "species_id": "brahmi",
        "common_name": "Brahmi",
        "scientific_name": "Bacopa monnieri",
        "synonyms": ["Water Hyssop", "Indian Pennywort", "Jalanimba"],
        "description": "Creeping marsh herb with succulent oblong leaves.",
        "medicinal_uses": "Memory enhancer; anxiety relief; neuro-protective.",
        "image_url": "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=600",
        "season_planting": "Apr-Jun",
        "season_harvest": "Oct-Dec",
        "default_unit_price_inr": 260.0,
    },
    {
        "species_id": "neem",
        "common_name": "Neem",
        "scientific_name": "Azadirachta indica",
        "synonyms": ["Margosa", "Indian Lilac", "Nimba"],
        "description": "Fast-growing tree with bitter compound leaves.",
        "medicinal_uses": "Antibacterial and antifungal; skin care; pest repellent; oral health.",
        "image_url": "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=600",
        "season_planting": "Jun-Sep",
        "season_harvest": "year-round",
        "default_unit_price_inr": 90.0,
    },
    {
        "species_id": "giloy",
        "common_name": "Giloy",
        "scientific_name": "Tinospora cordifolia",
        "synonyms": ["Guduchi", "Amrita", "Heart-leaved Moonseed"],
        "description": "Climbing shrub native to tropical India.",
        "medicinal_uses": "Immunity booster; antipyretic; supports liver function.",
        "image_url": "https://images.unsplash.com/photo-1591084728795-1149f32d9866?w=600",
        "season_planting": "Mar-Jun",
        "season_harvest": "Oct-Feb",
        "default_unit_price_inr": 210.0,
    },
    {
        "species_id": "amla",
        "common_name": "Amla",
        "scientific_name": "Phyllanthus emblica",
        "synonyms": ["Indian Gooseberry", "Amalaki", "Nellikai"],
        "description": "Deciduous tree with edible green-yellow sour fruit.",
        "medicinal_uses": "Vitamin C source; hair tonic; digestive aid; antioxidant.",
        "image_url": "https://images.unsplash.com/photo-1592844040408-bee6e6e1b9d8?w=600",
        "season_planting": "Jul-Aug",
        "season_harvest": "Nov-Feb",
        "default_unit_price_inr": 110.0,
    },
    {
        "species_id": "shatavari",
        "common_name": "Shatavari",
        "scientific_name": "Asparagus racemosus",
        "synonyms": ["Wild Asparagus", "Satawar", "Shatamuli"],
        "description": "Climbing perennial with feathery foliage and tuberous roots.",
        "medicinal_uses": "Female reproductive tonic; lactation support; adaptogen.",
        "image_url": "https://images.unsplash.com/photo-1597474561103-0d5dc0c46116?w=600",
        "season_planting": "Jul-Sep",
        "season_harvest": "Dec-Feb",
        "default_unit_price_inr": 290.0,
    },
    {
        "species_id": "haritaki",
        "common_name": "Haritaki",
        "scientific_name": "Terminalia chebula",
        "synonyms": ["Black Myrobalan", "Harad", "Karakkaya"],
        "description": "Large deciduous tree, one of the three Triphala fruits.",
        "medicinal_uses": "Digestive aid; mild laxative; rejuvenator.",
        "image_url": "https://images.unsplash.com/photo-1606326608690-4e0281b1e588?w=600",
        "season_planting": "Jun-Aug",
        "season_harvest": "Dec-Mar",
        "default_unit_price_inr": 240.0,
    },
    {
        "species_id": "bibhitaki",
        "common_name": "Bibhitaki",
        "scientific_name": "Terminalia bellirica",
        "synonyms": ["Beleric", "Baheda", "Aksha"],
        "description": "Tall deciduous tree, second of the Triphala fruits.",
        "medicinal_uses": "Respiratory support; digestive cleanser; eye health.",
        "image_url": "https://images.unsplash.com/photo-1606326608694-3e0d4b4f9a9e?w=600",
        "season_planting": "Jun-Aug",
        "season_harvest": "Nov-Feb",
        "default_unit_price_inr": 200.0,
    },
    {
        "species_id": "turmeric",
        "common_name": "Turmeric",
        "scientific_name": "Curcuma longa",
        "synonyms": ["Haldi", "Manjal", "Curcuma"],
        "description": "Rhizomatous herb with bright yellow inner root.",
        "medicinal_uses": "Anti-inflammatory; antioxidant; wound healing; spice.",
        "image_url": "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600",
        "season_planting": "Apr-May",
        "season_harvest": "Jan-Mar",
        "default_unit_price_inr": 160.0,
    },
    {
        "species_id": "ginger",
        "common_name": "Ginger",
        "scientific_name": "Zingiber officinale",
        "synonyms": ["Adrak", "Sunthi"],
        "description": "Rhizome with characteristic pungent aroma.",
        "medicinal_uses": "Digestive aid; anti-nausea; cold and cough relief.",
        "image_url": "https://images.unsplash.com/photo-1599301443434-3d9e6fb6d34d?w=600",
        "season_planting": "Mar-May",
        "season_harvest": "Dec-Feb",
        "default_unit_price_inr": 140.0,
    },
    {
        "species_id": "aloe-vera",
        "common_name": "Aloe Vera",
        "scientific_name": "Aloe barbadensis",
        "synonyms": ["Ghritkumari", "Kumari"],
        "description": "Succulent with thick fleshy leaves filled with gel.",
        "medicinal_uses": "Skin healing; burns and wound care; digestive support.",
        "image_url": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=600",
        "season_planting": "Feb-Apr",
        "season_harvest": "year-round",
        "default_unit_price_inr": 70.0,
    },
    {
        "species_id": "moringa",
        "common_name": "Moringa",
        "scientific_name": "Moringa oleifera",
        "synonyms": ["Drumstick Tree", "Sahjan", "Murungai", "Shigru"],
        "description": "Fast-growing tree with feathery leaves and long seed pods.",
        "medicinal_uses": "Nutrient-dense (iron, vitamins); anti-inflammatory; blood sugar support.",
        "image_url": "https://images.unsplash.com/photo-1605030753481-be2bf94d3b94?w=600",
        "season_planting": "Mar-Jun",
        "season_harvest": "year-round",
        "default_unit_price_inr": 130.0,
    },
    {
        "species_id": "ashoka",
        "common_name": "Ashoka",
        "scientific_name": "Saraca asoca",
        "synonyms": ["Sita Ashoka", "Anganapriya"],
        "description": "Small to medium evergreen tree with clusters of orange-red flowers.",
        "medicinal_uses": "Uterine tonic; menstrual disorders; skin health.",
        "image_url": "https://images.unsplash.com/photo-1592324872019-f31fa0a4e62a?w=600",
        "season_planting": "Jun-Aug",
        "season_harvest": "Feb-Apr",
        "default_unit_price_inr": 320.0,
    },
    {
        "species_id": "punarnava",
        "common_name": "Punarnava",
        "scientific_name": "Boerhavia diffusa",
        "synonyms": ["Spreading Hogweed", "Mukkarattai"],
        "description": "Spreading herb with small pink flowers, found across India.",
        "medicinal_uses": "Diuretic; kidney support; liver protector.",
        "image_url": "https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=600",
        "season_planting": "May-Jul",
        "season_harvest": "Oct-Dec",
        "default_unit_price_inr": 150.0,
    },
    {
        "species_id": "mulethi",
        "common_name": "Mulethi (Yashtimadhu)",
        "scientific_name": "Glycyrrhiza glabra",
        "synonyms": ["Licorice", "Yashtimadhu", "Jeshthamadhu"],
        "description": "Perennial legume with sweet roots.",
        "medicinal_uses": "Throat soother; cough relief; ulcer healing.",
        "image_url": "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=600",
        "season_planting": "Mar-May",
        "season_harvest": "Oct-Dec",
        "default_unit_price_inr": 220.0,
    },
    {
        "species_id": "kalmegh",
        "common_name": "Kalmegh",
        "scientific_name": "Andrographis paniculata",
        "synonyms": ["King of Bitters", "Bhunimba", "Mahatikta"],
        "description": "Annual herb with quadrangular stems and bitter taste.",
        "medicinal_uses": "Liver tonic; antipyretic; immune support.",
        "image_url": "https://images.unsplash.com/photo-1599308004193-5d3e30c95a7c?w=600",
        "season_planting": "Jun-Jul",
        "season_harvest": "Oct-Nov",
        "default_unit_price_inr": 180.0,
    },
    {
        "species_id": "stevia",
        "common_name": "Stevia",
        "scientific_name": "Stevia rebaudiana",
        "synonyms": ["Sweetleaf", "Sugarleaf"],
        "description": "Soft-leaved perennial herb whose leaves are intensely sweet.",
        "medicinal_uses": "Natural non-caloric sweetener; supports diabetes management.",
        "image_url": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600",
        "season_planting": "Mar-May",
        "season_harvest": "Aug-Nov",
        "default_unit_price_inr": 350.0,
    },
    {
        "species_id": "lemongrass",
        "common_name": "Lemongrass",
        "scientific_name": "Cymbopogon citratus",
        "synonyms": ["Citronella Grass", "Bhustrina", "Sera"],
        "description": "Aromatic tropical grass with lemony fragrance.",
        "medicinal_uses": "Digestive aid; insect repellent (essential oil); calming.",
        "image_url": "https://images.unsplash.com/photo-1547104442-9c50edc4d8d3?w=600",
        "season_planting": "Feb-Apr",
        "season_harvest": "year-round",
        "default_unit_price_inr": 80.0,
    },
    {
        "species_id": "vetiver",
        "common_name": "Vetiver (Khus)",
        "scientific_name": "Chrysopogon zizanioides",
        "synonyms": ["Khus", "Vetiveria", "Ushira"],
        "description": "Dense perennial bunch grass with deep aromatic roots.",
        "medicinal_uses": "Cooling agent; aromatic; root oil used in perfumery and Ayurveda.",
        "image_url": "https://images.unsplash.com/photo-1606925797300-0eb6e3b8d6c5?w=600",
        "season_planting": "May-Jul",
        "season_harvest": "Oct-Dec (year 2+)",
        "default_unit_price_inr": 270.0,
    },
    {
        "species_id": "sarpagandha",
        "common_name": "Sarpagandha",
        "scientific_name": "Rauvolfia serpentina",
        "synonyms": ["Indian Snakeroot", "Chandrika"],
        "description": "Evergreen shrub with milky sap.",
        "medicinal_uses": "Traditionally used for hypertension and as a sedative (regulated).",
        "image_url": "https://images.unsplash.com/photo-1608897547028-e1a4b95d432e?w=600",
        "season_planting": "Jun-Aug",
        "season_harvest": "Nov-Feb",
        "default_unit_price_inr": 450.0,
    },
    {
        "species_id": "kutki",
        "common_name": "Kutki",
        "scientific_name": "Picrorhiza kurroa",
        "synonyms": ["Katuki", "Hellebore"],
        "description": "Herb of the Himalayan ranges with creeping rootstock.",
        "medicinal_uses": "Liver protector; bile flow; antipyretic.",
        "image_url": "https://images.unsplash.com/photo-1610881111611-bc1bd2caaa7c?w=600",
        "season_planting": "Mar-May",
        "season_harvest": "Oct-Nov",
        "default_unit_price_inr": 520.0,
    },
    {
        "species_id": "mandukaparni",
        "common_name": "Mandukaparni",
        "scientific_name": "Centella asiatica",
        "synonyms": ["Gotu Kola", "Asian Pennywort"],
        "description": "Creeping perennial with kidney-shaped leaves.",
        "medicinal_uses": "Cognitive support; wound healing; skin health.",
        "image_url": "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=600",
        "season_planting": "Apr-Jun",
        "season_harvest": "Sep-Nov",
        "default_unit_price_inr": 240.0,
    },
    {
        "species_id": "guggul",
        "common_name": "Guggul",
        "scientific_name": "Commiphora wightii",
        "synonyms": ["Indian Bdellium", "Guggulu"],
        "description": "Thorny shrub yielding aromatic resin.",
        "medicinal_uses": "Cholesterol management; joint health; weight support.",
        "image_url": "https://images.unsplash.com/photo-1599300126937-71b34e5b3a87?w=600",
        "season_planting": "Jul-Sep",
        "season_harvest": "Oct-Dec (3+ years)",
        "default_unit_price_inr": 380.0,
    },
    {
        "species_id": "vasaka",
        "common_name": "Vasaka",
        "scientific_name": "Justicia adhatoda",
        "synonyms": ["Malabar Nut", "Adusa", "Adhatoda vasica"],
        "description": "Dense, evergreen shrub with strongly veined leaves.",
        "medicinal_uses": "Respiratory tonic; bronchitis and cough relief; expectorant.",
        "image_url": "https://images.unsplash.com/photo-1599300126937-71b34e5b3a87?w=600",
        "season_planting": "Jun-Aug",
        "season_harvest": "Sep-Dec",
        "default_unit_price_inr": 170.0,
    },
]
