# Generated by Django 5.2.6 on 2025-09-27 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='healthy', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('batch_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('quality_status', models.CharField(default='pending', max_length=64)),
                ('active_qr', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('transporter', 'Transporter'), ('lab', 'Lab'), ('processor', 'Processor'), ('consumer', 'Consumer'), ('admin', 'Admin'), ('manufacturer', 'Manufacturer')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('language_pref', models.CharField(default='en', max_length=10)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('transfer_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('from_owner', models.CharField(blank=True, max_length=64, null=True)),
                ('to_owner', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.herb')),
            ],
        ),
        migrations.AddField(
            model_name='herb',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_herbs', to='core.user'),
        ),
    ]
