# Generated by Django 4.2.8 on 2025-09-27 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('transport_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('transporter_id', models.CharField(max_length=64)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('gps_tracking_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='in_transit', max_length=64)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_records', to='core.herb')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('report_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('lab_id', models.CharField(max_length=64)),
                ('test_type', models.CharField(max_length=100)),
                ('results_summary', models.TextField()),
                ('certification', models.BooleanField(default=False)),
                ('certification_level', models.CharField(blank=True, max_length=50, null=True)),
                ('report_url', models.URLField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('purity_percentage', models.FloatField(blank=True, null=True)),
                ('moisture_content', models.FloatField(blank=True, null=True)),
                ('ash_content', models.FloatField(blank=True, null=True)),
                ('heavy_metals_present', models.BooleanField(default=False)),
                ('pesticides_detected', models.BooleanField(default=False)),
                ('active_compounds', models.TextField(blank=True, null=True)),
                ('potency_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='core.herb')),
            ],
        ),
    ]
