# Generated by Django 4.2.8 on 2025-09-27 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transportrecord_labreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='herb',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_herbs', to='core.user'),
        ),
        migrations.AddField(
            model_name='herb',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
