# Generated by Django 4.2.8 on 2025-09-27 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_herb_created_at_herb_current_owner_herb_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershiptransfer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='status',
            field=models.CharField(default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='transfer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
